In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

/home/limhyesu/anaconda3/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# One cell RNN input_dim (4) -> output_dim (2)
hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size) # output dimension이 2인 cell 생성

# input
x_data = np.array([[[1,0,0,0]]], dtype = np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

In [3]:
sess.run(tf.global_variables_initializer()) # variable을 초기화하고 실행함.
pp.pprint(outputs.eval())

array([[[-0.08110873,  0.09853155]]], dtype=float32)


In [4]:
# One hot encoding for each char in 'hello'
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

In [9]:
# One cel RNN input_dim (4) -> output_dim (2). sequence : 5
x_data_2 = np.array([[h,e,l,l,o]], dtype=np.float32)
print(x_data_2.shape)
pp.pprint(x_data_2)
outputs_2, states = tf.nn.dynamic_rnn(cell, x_data_2, dtype=tf.float32)
sess.run(tf.global_variables_initializer())
pp.pprint(outputs_2.eval())

(1, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
array([[[-0.06047141, -0.00438683],
        [-0.11428346, -0.10265477],
        [-0.04618637, -0.02500629],
        [-0.01184013,  0.03899765],
        [-0.0672038 ,  0.09298304]]], dtype=float32)


In [11]:
# One cel RNN input_dim (4) -> output_dim (2). sequence : 5, batch : 3
x_data_3 = np.array([[h,e,l,l,o], [e,o,l,l,l], [l,l,e,e,l]], dtype=np.float32)
print(x_data_3.shape)
print()
pp.pprint(x_data_3)
outputs_3, states = tf.nn.dynamic_rnn(cell, x_data_3, dtype=tf.float32)
sess.run(tf.global_variables_initializer())
print()
pp.pprint(outputs_3.eval())

(3, 5, 4)

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)

array([[[ 0.12390857, -0.11472706],
        [ 0.03512599, -0.18473887],
        [-0.05325012, -0.03150684],
        [-0.09872831,  0.02119573],
        [ 0.03261034, -0.0633303 ]],

       [[-0.0301294 , -0.10660589],
        [ 0.05872541, -0.11070183],
        [-0.01972193, -0.04362303],
        [-0.07841022,  0.01658935],
        [-0.11119507,  0.04833953]],

       [[-0.06230262,  0.04540988],
        [-0.09879838,  0.06811427],
        [-0.09600377, -0.04347256],
        [-0.10834204, -0.13600145],
        [-0.14168037, -0.02676033]]], dtype=float32)
